[package]
name = "libp2p_learning"
version = "0.2.0"
authors = ["jamie"]
edition = "2018"

[dependencies]
env_logger = "0.7"
futures = "0.3.14"
hex = "0.4.3"
libp2p = "0.37"
log = "0.4"
pin-project = "1.0.7"
tokio = { version = "1.5.0", features = ["full"]}
