[package]
name = "libp2p_learning"
version = "0.1.0"
authors = ["jamie"]
edition = "2018"

[dependencies]
env_logger = "0.7"
futures = "0.3.5"
hex = "0.4"
libp2p = { version = "0.19" }
log = "0.4"
pin-project = "0.4"
tokio = { version = "0.2.21", features = ["full"]}